Performance & Convenience Tweaks for NGINX HTTP to HTTPS Proxy
ONLYOFFICE/document-server-proxy pull request #15
Opened 2020-01-14 23:40 UTC by aknobloch

Makes the following adjustments to the NGINX HTTP to HTTPS config:

- Removes `root` directive in the HTTP server block, I don't believe this has any functional use.
- Replaces `rewrite` directive with `return` directive for the HTTP redirect. This is for performance and readability, and is advised [by NGINX here](https://www.nginx.com/resources/wiki/start/topics/tutorials/config_pitfalls/#taxing-rewrites).
- Disable the Strict-Transport-Security header by default, since this can cause headaches when doing initial setup and isn't critical to secure SSL transport.
- Modify suggested Strict-Transport-Security header to include subdomains and be sent always.

I'm pretty new to NGINX, but these are some things I've observed and found while messing around. Please take a close look at the changes and let me know if I'm ignorant of something. Thanks!

2021-03-22 08:38 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/ONLYOFFICE/document-server-proxy?pullRequest=15) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/ONLYOFFICE/document-server-proxy?pullRequest=15) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/ONLYOFFICE/document-server-proxy?pullRequest=15) it.</sub>

2021-03-22 08:54 UTC, aknobloch commented
Signed the CLA, let me know if there are any questions. Thanks!

2021-03-22 09:03 UTC, agolybev requested changes

2021-03-22 09:07 UTC, agolybev commented
Hi @aknobloch, sorry for the delay. I added a review but didn't submit it.

2021-06-19 21:25 UTC, aknobloch commented on nginx/proxy-https-to-http.conf
> +  return 301 https://$server_name:443$request_uri;
443 is the standard SSL port, and the next block in this config specifies it:
```
server {
  listen 0.0.0.0:443 ssl;
  listen [::]:443 ssl default_server;
```
So, per this example configuration, we need to redirect to 443.

2021-06-19 21:32 UTC, aknobloch commented on nginx/proxy-https-to-http.conf
> +  ## [Optional] Before enabling Strict-Transport-Security headers please read into this topic first.
Great idea, thanks! Added.

2021-06-19 21:33 UTC, aknobloch commented
Thanks for the review @agolybev. My apologies for the delay as well.

2021-06-24 14:10 UTC, agolybev approved these changes

2021-06-24 14:12 UTC, merged